export { NETWORK_ERROR } from './errors';
export {
    LOGIN,
    APPLICANTS_LIST_STATUS,
    APPLICANTS_BY_ID,
    APPROVE_OR_DECLINE_APPLICANTS,
    SIGNUP,
    RESET_PASSWORD,
    UPDATE_PASSWORD,
} from './endPoints';